{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-groupedstats
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/groupedstats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/groupedstats/groupedstats_{{ version }}.tar.gz
  sha256: b50ae9c83efc4e5cd4d93a4d3427b924a13c767f3a2b1b6d496c30a82df2dd7e

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-broomextra >=0.0.5
    - r-dplyr >=0.8.3
    - r-glue >=1.3.1
    - r-haven
    - r-ipmisc
    - r-lme4 >=1.1_21
    - r-parameters
    - r-purrr >=0.3.2
    - r-rlang >=0.4.0
    - r-rstudioapi >=0.9.0
    - r-sjstats >=0.17.5
    - r-skimr >=1.0.7
    - r-tibble >=2.1.3
    - r-tidyr >=0.8.3
  run:
    - r-base
    - r-broomextra >=0.0.5
    - r-dplyr >=0.8.3
    - r-glue >=1.3.1
    - r-haven
    - r-ipmisc
    - r-lme4 >=1.1_21
    - r-parameters
    - r-purrr >=0.3.2
    - r-rlang >=0.4.0
    - r-rstudioapi >=0.9.0
    - r-sjstats >=0.17.5
    - r-skimr >=1.0.7
    - r-tibble >=2.1.3
    - r-tidyr >=0.8.3

test:
  commands:
    - $R -e "library('groupedstats')"           # [not win]
    - "\"%R%\" -e \"library('groupedstats')\""  # [win]

about:
  home: https://indrajeetpatil.github.io/groupedstats/, https://github.com/IndrajeetPatil/groupedstats/
  license: GPL-3
  summary: Collection of functions to run statistical tests across all combinations of multiple grouping variables.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: groupedstats
# Title: Grouped Statistical Analyses in a Tidy Way
# Version: 0.0.9
# Authors@R:  person(given = "Indrajeet", family = "Patil", role = c("aut", "cre"), email = "patilindrajeet.science@gmail.com", comment = c(ORCID = "0000-0003-1995-6531"))
# Maintainer: Indrajeet Patil <patilindrajeet.science@gmail.com>
# Description: Collection of functions to run statistical tests across all combinations of multiple grouping variables.
# License: GPL-3 | file LICENSE
# URL: https://indrajeetpatil.github.io/groupedstats/, https://github.com/IndrajeetPatil/groupedstats/
# BugReports: https://github.com/IndrajeetPatil/groupedstats/issues/
# Depends: R (>= 3.5.0)
# Imports: broomExtra (>= 0.0.5), crayon (>= 1.3.4), dplyr (>= 0.8.3), glue (>= 1.3.1), lme4 (>= 1.1-21), magrittr (>= 1.5), purrr (>= 0.3.2), rlang (>= 0.4.0), robust (>= 0.4-18.1), rstudioapi (>= 0.9.0), sjstats (>= 0.17.5), skimr (>= 1.0.7), stats, tibble (>= 2.1.3), tidyr (>= 0.8.3), utils
# Suggests: ez, gapminder, ggplot2, knitr, rmarkdown, spelling, testthat
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 6.1.1.9000
# NeedsCompilation: no
# Packaged: 2019-08-28 12:35:29 UTC; inp099
# Author: Indrajeet Patil [aut, cre] (<https://orcid.org/0000-0003-1995-6531>)
# Repository: CRAN
# Date/Publication: 2019-08-28 13:30:02 UTC
